name: Build Python 3.12 for Bullseye

on:
  workflow_dispatch:   # manual trigger
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    container: debian:bullseye   # <-- build inside Bullseye

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y \
            build-essential \
            libssl-dev zlib1g-dev libncurses5-dev libffi-dev \
            libsqlite3-dev libreadline-dev libbz2-dev \
            liblzma-dev tk-dev wget ca-certificates

      - name: Download Python 3.12.7 source
        run: |
          wget https://www.python.org/ftp/python/3.12.7/Python-3.12.7.tgz
          tar -xf Python-3.12.7.tgz
          mv Python-3.12.7 python-src

      - name: Build Python
        run: |
          cd python-src
          ./configure --prefix=/opt/python312
          make -j2
          make install

      - name: Package result
        run: |
          tar -czf python312-bullseye-x86_64.tar.gz -C /opt python312

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python312-bullseye
          path: python312-bullseye-x86_64.tar.gz
