name: Build VLC 3.0.17.4 for Debian Bullseye

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:bullseye

    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y \
            build-essential pkg-config git curl wget \
            automake autoconf libtool \
            libxcb1-dev libxcb-shm0-dev libxcb-xv0-dev \
            libxcb-keysyms1-dev libxcb-randr0-dev \
            libxcb-xinerama0-dev libxcb-composite0-dev \
            libxcb-xfixes0-dev libxcb-shape0-dev \
            libxcb-image0-dev \
            libx11-dev libxext-dev \
            libgl1-mesa-dev libglu1-mesa-dev \
            libasound2-dev libpulse-dev \
            libdbus-1-dev libsystemd-dev \
            libfreetype6-dev libfribidi-dev libharfbuzz-dev \
            liba52-0.7.4-dev libdca-dev libdvbpsi-dev \
            libdvdnav-dev libdvdread-dev \
            libmad0-dev libmpeg2-4-dev \
            libogg-dev libvorbis-dev libflac-dev libopus-dev \
            libtheora-dev libx264-dev

      - name: Download VLC 3.0.17.4 source
        run: |
          wget https://download.videolan.org/pub/videolan/vlc/3.0.17.4/vlc-3.0.17.4.tar.xz
          tar xf vlc-3.0.17.4.tar.xz
          cd vlc-3.0.17.4
          ./bootstrap

      - name: Configure and Build VLC
        run: |
          cd vlc-3.0.17.4
          ./configure --prefix=/usr
          make -j$(nproc)
          make install DESTDIR=./out

      - name: Archive Build
        uses: actions/upload-artifact@v4
        with:
          name: vlc-3.0.17.4-bullseye
          path: vlc-3.0.17.4/out
